  version: "3.7"

  services:
    gitea.com:
      image: gitea/gitea
      container_name: "gitea.com"
      restart: "unless-stopped"

      volumes:
        - ./gitea:/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    
      networks:
        - ci
          # ipv4_address: 172.20.0.5

#      ports:
#         - 80:3000
        # - 2222:22

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gitea.rule=Host(`gitea.com`)"
        - "traefik.http.routers.gitea.entrypoints=web,websecure"
        - "traefik.http.services.gitea.loadbalancer.server.port=3000"
        # - "traefik.http.routers.gitea.middlewares=test-auth"
        # - "traefik.http.middlewares.test-auth.basicauth.users=shankar:$$apr1$$jwFDr9ud$$GKf3mO2BuMUFVHHmwkhM//"
        - "traefik.docker.network=gitea_ci"


      # healthcheck:

        #   - test: ["CMD- SHELL", "/bin/s6-svok", "/etc/s6/gitea || exit 1"]
        #   - interval: 30s
        #   - timeout: 3s
        #   - retries: 3
        #   - start_peroid: 10s  

    drone.in:
      image: drone/drone:2
      container_name: "drone.in"
      volumes:
        - ./droneserver:/var/lib/drone
      restart: always

      environment:

        - DRONE_RPC_SECRET=84b82fc6c090f334e40edfeeb0f46932
        - DRONE_SERVER_HOST=drone.in
        - DRONE_SERVER_PROTO=http
        - DRONE_TLS_AUTOCERT=false
        - DRONE_GIT_ALWAYS_AUTH=true
        - DRONE_GITEA_SERVER=http://gitea.com
        - DRONE_RUNNER_NETWORKS=gitea_ci

      env_file:
        - .env

      networks:
        - ci
          # ipv4_address: 172.20.0.6

      # ports:
      #   - 80:80
        # - 2222:22

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drone-server.rule=Host(`drone.in`)"
        - "traefik.http.routers.drone-server.entrypoints=web,websecure"
        - "traefik.http.services.drone-server.loadbalancer.server.port=80"
        - "traefik.docker.network=gitea_ci"

    drone-runner:
      image: drone/drone-runner-docker:1
      container_name: runner
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - DRONE_RPC_PROTO=http
        - DRONE_RPC_HOST=drone.in
        - DRONE_RPC_SECRET=84b82fc6c090f334e40edfeeb0f46932
        - DRONE_RUNNER_CAPACITY=2
        - DRONE_RUNNER_NAME=runner
        - DRONE_RUNNER_NETWORKS=gitea_ci

      restart: unless-stopped
      networks:
        - ci
          # ipv4_address: 172.20.0.7

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drone-runner.entrypoints=web,websecure"
        - "traefik.http.services.drone-runner.loadbalancer.server.port=3000"
        - "traefik.docker.network=gitea_ci"


      # ports:
      #   - 3001:3000
        # - 2222:22


  networks:
    ci:
      driver: bridge
      # external: true
      # ipam:
      #   config:
      #     - subnet: 172.20.0.0/24
